### ISSUE TITLE
Suggestion: Gemma 2 9B and 27B.

### ISSUE THREAD

**Issue by kaykyr** [uclaml/SPPO#3]
Imagine how these models could performs even better using SPPO.

**Comment by angelahzyuan** [comment]
Thank you for your suggestions. Check our latest release at https://huggingface.co/UCLA-AGI/Gemma-2-9B-It-SPPO-Iter3. With a 53.27 LC-win rate.

**Comment by kaykyr** [comment]
I appreciate it! Thanks!

Can you share the code for this 9B model? I intent to do the same for 27B.
